export const STATES = [
  { value: '', text: '', taxRate: 0 },
  { value: 'AL', text: 'Alabama', taxRate: 4.0 },
  { value: 'AK', text: 'Alaska', taxRate: 0.0 },
  { value: 'AZ', text: 'Arizona', taxRate: 5.6 },
  { value: 'AR', text: 'Arkansas', taxRate: 7.25 },
  { value: 'CA', text: 'California', taxRate: 7.25 },
  { value: 'CO', text: 'Colorado', taxRate: 2.9 },
  { value: 'CT', text: 'Connecticut', taxRate: 6.35 },
  { value: 'DE', text: 'Delaware', taxRate: 0 },
  { value: 'DC', text: 'District Of Columbia', taxRate: 6.0 },
  { value: 'FL', text: 'Florida', taxRate: 6.0 },
  { value: 'GA', text: 'Georgia', taxRate: 4.0 },
  { value: 'HI', text: 'Hawaii', taxRate: 4.0 },
  { value: 'ID', text: 'Idaho', taxRate: 6.0 },
  { value: 'IL', text: 'Illinois', taxRate: 6.25 },
  { value: 'IN', text: 'Indiana', taxRate: 7.0 },
  { value: 'IA', text: 'Iowa', taxRate: 6.0 },
  { value: 'KS', text: 'Kansas', taxRate: 6.5 },
  { value: 'KY', text: 'Kentucky', taxRate: 6.0 },
  { value: 'LA', text: 'Louisiana', taxRate: 4.45 },
  { value: 'ME', text: 'Maine', taxRate: 5.5 },
  { value: 'MD', text: 'Maryland', taxRate: 6.0 },
  { value: 'MA', text: 'Massachusetts', taxRate: 6.25 },
  { value: 'MI', text: 'Michigan', taxRate: 6.0 },
  { value: 'MN', text: 'Minnesota', taxRate: 6.875 },
  { value: 'MS', text: 'Mississippi', taxRate: 7.0 },
  { value: 'MO', text: 'Missouri', taxRate: 4.225 },
  { value: 'MT', text: 'Montana', taxRate: 0.0 },
  { value: 'NE', text: 'Nebraska', taxRate: 5.5 },
  { value: 'NV', text: 'Nevada', taxRate: 6.85 },
  { value: 'NH', text: 'New Hampshire', taxRate: 0.0 },
  { value: 'NJ', text: 'New Jersey', taxRate: 6.625 },
  { value: 'NM', text: 'New Mexico', taxRate: 5.125 },
  { value: 'NY', text: 'New York', taxRate: 4.0 },
  { value: 'NC', text: 'North Carolina', taxRate: 4.75 },
  { value: 'ND', text: 'North Dakota', taxRate: 5.0 },
  { value: 'OH', text: 'Ohio', taxRate: 5.75 },
  { value: 'OK', text: 'Oklahoma', taxRate: 4.5 },
  { value: 'OR', text: 'Oregon', taxRate: 0.0 },
  { value: 'PA', text: 'Pennsylvania', taxRate: 6.0 },
  { value: 'RI', text: 'Rhode Island', taxRate: 7.0 },
  { value: 'SC', text: 'South Carolina', taxRate: 6.0 },
  { value: 'SD', text: 'South Dakota', taxRate: 4.5 },
  { value: 'TN', text: 'Tennessee', taxRate: 7.0 },
  { value: 'TX', text: 'Texas', taxRate: 6.25 },
  { value: 'UT', text: 'Utah', taxRate: 4.85 },
  { value: 'VT', text: 'Vermont', taxRate: 6.0 },
  { value: 'VA', text: 'Virginia', taxRate: 4.3 },
  { value: 'WA', text: 'Washington', taxRate: 6.5 },
  { value: 'WV', text: 'West Virginia', taxRate: 6.0 },
  { value: 'WI', text: 'Wisconsin', taxRate: 5.0 },
  { value: 'WY', text: 'Wyoming', taxRate: 4.0 },
];
